package config

type AutoGenerated struct {
	Db struct {
		DbType string `json:"dbType"`
		Detail struct {
			Host        string `json:"host"`
			Port        int    `json:"port"`
			User        string `json:"user"`
			Password    string `json:"password"`
			Schema      string `json:"schema"`
			MaxPoolSize int    `json:"maxPoolSize"`
			MaxIdleSize int    `json:"maxIdleSize"`
		} `json:"detail"`
	} `json:"db"`
	Logging struct {
		File       string `json:"file"`
		Level      string `json:"level"`
		MaxAge     int    `json:"maxAge"`
		MaxSize    int    `json:"maxSize"`
		MaxBackups int    `json:"maxBackups"`
		Compress   bool   `json:"compress"`
	} `json:"logging"`
	Redis struct {
		Host     string `json:"host"`
		Port     int    `json:"port"`
		IndexDb  int    `json:"indexDb"`
		User     string `json:"user"`
		Password string `json:"password"`
	} `json:"redis"`
	Store struct {
		Cache struct {
			Type   string `json:"type"`
			Detail struct {
				Expire          int    `json:"expire"`
				UseSSL          bool   `json:"useSSL"`
				AccessID        string `json:"accessID"`
				EndPoint        string `json:"endPoint"`
				SecretAccessKey string `json:"secretAccessKey"`
			} `json:"detail"`
		} `json:"cache"`
		Lasting struct {
			Type   string `json:"type"`
			Detail struct {
			} `json:"detail"`
		} `json:"lasting"`
	} `json:"store"`
	Forward struct {
		AppDebug           bool   `json:"appDebug"`
		MsgEncodeKey       string `json:"msgEncodeKey"`
		MaxRecount         int    `json:"maxRecount"`
		HealthyInterval    int    `json:"healthyInterval"`
		AlgoManageProtocol string `json:"AlgoManageProtocol"`
		AlgoManageURL      string `json:"AlgoManageUrl"`
		CasbinModel        string `json:"casbinModel"`
		Cert               string `json:"cert"`
		KeyFile            string `json:"keyFile"`
		JwtSignKey         string `json:"jwtSignKey"`
		JwtOnlineUsers     int    `json:"jwtOnlineUsers"`
		JwtExpireAt        int    `json:"jwtExpireAt"`
		IsRedis            bool   `json:"isRedis"`
	} `json:"forward"`
}
